### ISSUE TITLE
volume

### ISSUE THREAD

**Issue by joassouza** [phocean/dockerfile-etherpad#1]
Hello @phocean. I've a problem quite similar to yours. I need to load some etherpad plugins and be able to change the code locally and reflect in the containe (for dev purpose, of course). I've tried to use volume but it doesn't work.
Any idea how to achieve this?
Thanks for making this dockerfile public. =)

**Comment by phocean** [comment]
Hi @joassouza ,
The volume in my Dockerfile is only for the database.
So, you need to add a new VOLUME in the Dockerfile pointing to the directory where your dev files are found and then use another -v option at run time.
There are probably other ways, but this is how I would do (I do  have such similar settings for other projects).
